all:
	gcc seq.c -o seq -Wall -fopenmp -lm
	gcc par.c -o par -Wall -fopenmp -lm

run_seq:
	echo "Sequencial:"
	./seq <(./generator 43 700 10000)
run_par:
	echo ""lelo:
	./pa./par <(nerator 43 700 10000) | )